### ISSUE TITLE
convert 'npm run' scripts to 'nps' in init

### ISSUE THREAD

**Issue by benmonro** [kentcdodds/nps#107]
Problem description:

currently if you run `nps init` on a script, it just copies over your scripts verbatim.  it would be nice if it any scripts I have which execute other scripts would be converted to nps (since they also moved).

Suggested solution:

```json
scripts:{
  "blah": "npm run blah:ext && echo hello",
  "blah:ext": "echo hello2"
}
```

would get init'd as:
```yaml
scripts:
  blah:
    default: nps blah.ext && echo hello
    ext: echo hello2

**Comment by kentcdodds** [comment]
Super! Definitely feel like this would help people with migrating. Same as #108. Anyone care to [makeapullrequest.com](http://makeapullrequest.com)? The relevant code is [here](https://github.com/kentcdodds/p-s/blob/master/src/bin-utils/initialize/index.js).

**Comment by Miklet** [comment]
Issue #128 included requested feature so we can close it 🙂
