### ISSUE TITLE
should "prettier-eslint-cli" be a devDependency instead?

### ISSUE THREAD

**Issue by rrag** [kentcdodds/nps#112]
- `nps` version:
```
./node_modules/.bin/nps --version
5.0.2
```

- `node` version:
```
node --version
v7.5.0
```

- `npm` version:
```
npm --version
4.1.2
```
Problem description:

I just installed `nps` and it installed 91 modules, I have recently been trying to understand why certain dependencies are added and try to reduce some if possible.

```
> yarn add -D nps
yarn add v0.20.3
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 91 new dependencies.
├─ abbrev@1.1.0
├─ arrify@1.0.1
...
```
analysed a few of these with `yarn why`

```
$ yarn why rxjs
info This module exists because "nps#prettier-eslint-cli" depends on it.

$ yarn why babel-code-frame
info Reasons this module exists
   - "nps#prettier-eslint-cli#prettier-eslint#prettier" depends on it
```

Suggested solution:

Should this be a dev dependency instead?

**Comment by kentcdodds** [comment]
Yes, it definitely should. My mistake. Could you submit a pull request? http://makeapullrequest.com

**Comment by rrag** [comment]
thank you that was very quick
