### ISSUE TITLE
Remove out-dated README note

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/nps#117]
:1st_place_medal: This is a [first-timers-only](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) issue! That means that I will only accept a pull request to fix this issue from someone who's never contributed to an open source project before! :tada:

> Note: you might find this to be a helpful: ["How to Contribute to an Open Source Project on GitHub"](http://kcd.im/pull-request)

**Here's the issue:**

Recently, this project was renamed from `p-s` to `nps`. Before the rename, `p-s` exposed an alias binary called `nps` so you could type it faster. This was documented in the README so people could use that alias binary if they wanted. However, when I did the rename, I mistakenly forgot to remove that documentation. And because the wonders of find and replace, the documentation now reads kinda funny (as [noted](https://twitter.com/naholyr/status/832865527659888640) to me... [twice](https://twitter.com/rossipedia/status/834176117242265602) :sweat_smile:):

![nps](https://cloud.githubusercontent.com/assets/1500684/23189557/a3643bd6-f850-11e6-9f59-9310ea3408be.jpg)

**Here's what we need:**

We need that paragraph removed entirely.

**Here's how you do it:**

> remember, the object of this issue is not for you to do something complicated, it's for you to have experience contributing to an open source project. So I'm going to tell you exactly what to do. Good luck!

1. Fork the project, clone your fork, and make a branch for your fix - learn about how to do this in [the course](http://kcd.im/pull-request) referenced above.
2. Setup the project by following [these instructions](https://github.com/kentcdodds/nps/blob/master/CONTRIBUTING.md#project-setup)
3. Remove the paragraph that starts with "Because nps is harder to type..."
4. Add yourself to [the contributors table](https://github.com/kentcdodds/nps/blob/master/README.md#contributors) by following [these instructions](https://github.com/kentcdodds/nps/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor)
5. commit your changes following [the commit message conventions](https://github.com/conventional-changelog/conventional-changelog-angular/blob/master/convention.md) (or you can run `git add -A && npm start commit` and follow the prompt).
6. push your branch to your fork, and create a pull request - learn about how to do this in [the course](http://kcd.im/pull-request) referenced above.
7. Wait patiently while I review it.
8. Respond to any feedback
9. Get merged
10. Celebrate! :tada:

Thanks so much!

P.S. I'm available to chat [on gitter](https://gitter.im/kentcdodds) if you need help!

**Comment by kentcdodds** [comment]
Please claim the issue by commenting here!

**Comment by JasonSooter** [comment]
@kentcdodds I'd be happy to do it

**Comment by kentcdodds** [comment]
Awesome! Let me know if you need any help @JasonSooter!

**Comment by JasonSooter** [comment]
@kentcdodds Well I hope I did it correctly. Thanks for the nice video series to make it clear ;-)

**Comment by kentcdodds** [comment]
Thanks @JasonSooter!
