### ISSUE TITLE
Add option to display only name and description for help command

### ISSUE THREAD

**Issue by gunnx** [kentcdodds/nps#119]
- `nps` version: 5.0.3
- `node` version: 7.4.0
- `npm` version: 4.0.5

Problem description:
Some scripts can be very long making the help output harder to read.

Suggested solution:
Either remove displaying the script completely, or supply a way to configure help so you can hide the script output, this could be done via a flag, or perhaps per script in the config file, much like `hiddenFromHelp` works, could even use that and change it from a boolean to other option like: `hiddenFromHelp: 'script'`

**Comment by kentcdodds** [comment]
Thanks. Definitely open to doing this. Just unsure of what's best. I think I like using hiddenFromHelp, but what does everyone else think?

**Comment by robwise** [comment]
For me, I like this idea because I like using `nps` as a menu of what I might want to run, but usually I'm not interested in looking at the source script code, I just want the names and maybe the descriptions. Accomplishing that by adding an option on a per-script basis would be kind of un-DRY. 

What about just adding a built-in nps command called "commands" or a flag? I guess you might be worried about name conflicts though. But this way you could just make your script:

```
  "start": "nps commands",
```

**Comment by kentcdodds** [comment]
What if it was just `nps help --no-scripts`?

**Comment by robwise** [comment]
Well if it's going to be based off of `help`, then we should also remove this type of thing with that flag:

```
Usage: node_modules/.bin/nps [options] <script>...

Commands:
  init        automatically migrate from npm scripts to nps
  completion  generate bash completion script

Options:
  --config, -c     Config file to use (defaults to nearest package-scripts.yml
                   or package-scripts.js)                              [default:
         "/Users/Rob/dev/shakacode/friendsandguests/client/package-scripts.yml"]
  --silent, -s     Silent nps output                  [boolean] [default: false]
  --log-level, -l  The log level to use
                   [choices: "error", "warn", "info", "debug"] [default: "info"]
  --require, -r    Module to preload
  -h, --help       Show help                                           [boolean]
  -v, --version    Show version number                                 [boolean]

Examples:
  node_modules/.bin/nps test build          Runs the `test` script then the
                                            `build` script
  node_modules/.bin/nps "test --cover"      Runs the `test` script and forwards
  "build --prod"                            the "--cover" flag then the `build`
                                            script and forwards the "--prod"
                                            flag
```

The idea being I know how to use nps, I just forgot the name of the script, but I'll know it when I see it?

**Comment by kentcdodds** [comment]
Good point!

**Comment by RichDonnellan** [comment]
Piggybacking on this idea, can we also include a way to hide the script output when executing `nps`? Really long scripts do clutter the log and shouldn't be important to see once your setup is "bulletproof".

```shell
[PREFIX] nps is executing `task`: <script displayed here and could be really looooong spanning multiple lines> // nope
[PREFIX] nps is executing `next task`: <script displayed here and could be really looooong spanning multiple lines> // nope

[PREFIX] nps is executing `task` // yep
[PREFIX] nps is executing `next task` // yep
```

**Comment by iamkether** [comment]
@kentcdodds What do you think about this format:

```javascript
options: {
    'help-style': 'basic' // 'all', 'scripts' 
}
```
`all` would be the default and basically gives you the entire output like the command does currently. `scripts` would be something like this:
```
default - Get help on what commands are available - nps help
commit - Start a new commit with commitizen - git-cz
dev - Run the Webpack HMR Dev Server - node ./build/dev-server.js
build - Build the Project for deployment  - node ./build/build.js
test - Run all of the tests for the app - node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names 
```

And then `basic` would give it to you without the scripts appended to the end:
```
default - Get help on what commands are available
commit - Start a new commit with commitizen
dev - Run the Webpack HMR Dev Server
build - Build the Project for deployment
test - Run all of the tests for the app
```

**Comment by kentcdodds** [comment]
Sounds fine to me!

Let's just make sure it's tested and documented too! 👍

**Comment by iamkether** [comment]
@kentcdodds I've mostly figured out how to do this, but I want some feedback on my direction in case I'm missing something in the library. Is there a way to globally access the current options object? Or do I need to re-write functions all the way up the call stack to carry the options object down to the right functions?

**Comment by kentcdodds** [comment]
@iamkether, what you have there seems fine to me :+1:

**Comment by iamkether** [comment]
This was fixed in https://github.com/kentcdodds/nps/pull/164. You can now specify a `'help-style'` in your `config.options` object see my [above message](https://github.com/kentcdodds/nps/issues/119#issuecomment-330034525) for details on what each option provides for output.
