### ISSUE TITLE
"nps init" should not touch core npm script "hooks" 

### ISSUE THREAD

**Issue by ghost** [kentcdodds/nps#128]
While executing `nps init` all scripts are moved to nps including nps script "hooks" e.g. "preinstall" or "prepublish". That kind of scripts should be treated same as "test" script - kept in package.json with a conversion of the content of script to nps.

List of hooks we would need to address:
[https://docs.npmjs.com/misc/scripts](url)

**Comment by kentcdodds** [comment]
This is a dupe of #97 :)
