### ISSUE TITLE
`silent` and `logLevel` option

### ISSUE THREAD

**Issue by luftywiranda13** [kentcdodds/nps#141]
- `nps` version: v5.3.1
- `node` version: v7.10.0
- `npm` version: v4.6.1

Scripts file (or at least the relevant bits):

in `package-scripts.js`
```javascript
options: {
 silent: true,
},
```
or 
```js
options: {
  logLevel: 'warn',
},
```

The command executed:

```sh
# with npm
npm start `anything`

# with yarn
yarn start `anything`

# or globally installed `nps`
nps `anything`
```

The output:
no differences, the output is still the same just like there's no option is configured.

Problem description:
I need to tame the verbosity of the output a little bit, because I think nps is too 'noisy' with default settings.

But is it me or am I doing the `options` wrong?

**Comment by Miklet** [comment]
Is your `options` property at the same depth as `scripts`? What I mean:
```
module.exports = {
  scripts: {
    ...
  },
  options: {
    silent: true
  }
}
```

**Comment by luftywiranda13** [comment]
@Miklet yes, I set `scripts` and `options` at the same level
pretty much like this https://github.com/kentcdodds/nps/blob/master/package-scripts.js#L66

**Comment by Miklet** [comment]
@kentcdodds Alright, I did some investigation and probably found a reason. In `nps.js` we do merge of options from `package-scripts.js` and cmd options. Command line options take precedence and since values for logLevel and silence are not provided they receive their default values which is `false` for silent and `'info'` for `logLevel`.

**Comment by luftywiranda13** [comment]
@Miklet so it means any `options` I set in `package-scripts.js` will always be ignored?

**Comment by Miklet** [comment]
I think yes :( But I also want to wait for @kentcdodds comment. Btw. you can still pass `-s` or `--silent` option to make nps less noicy until it will be fixed.

**Comment by kentcdodds** [comment]
Yep, that sounds like the problem. The food would be to remove the CLI defaults I think. Happy to accept a [pull request](http://makeapullrequest.com) 😀

**Comment by luftywiranda13** [comment]
sure, but I need times to figure out how `nps` works first 😁

**Comment by kentcdodds** [comment]
Take your time :) It's as urgent as you need it to be :)

**Comment by Songworks** [comment]
Had a look into this and there don't seem to be too many complex changes necessary to fix it, theoretically anyway. Still accepting a PR for this?

**Comment by kentcdodds** [comment]
Sure 👍

**Comment by kevjin** [comment]
Made a PR above that would finally fix this issue. :)
