### ISSUE TITLE
Add option to hide script description on nps execution

### ISSUE THREAD

**Issue by RichDonnellan** [kentcdodds/nps#143]
- `nps` version: 5.3.1
- `node` version: 8.1.0
- `npm` version: 5.0.3

**Problem description:**
After executing `nps`, the script description is logged. This can clutter the displayed output if running lengthy scripts.

```shell
nps is executing `build`: `nps clean --config ${configFile} && concurrently --kill-others-
on-fail --prefix name --names \'COMPILE,BUILD\' --prefix-colors \'bgBlack.bold,bgCyan.bold\'
\'nps compile --config ${configFile}\' \'nps build --config ${configFile}\'`
nps is executing `compile`: `concurrently --kill-others-on-fail --prefix name --names \'SCSS,JS\'
--prefix-colors \'bgGreen.bold,bgRed.bold\' \'nps compile.scss --config ${configFile}\' \'nps
compile.js --config ${configFile}\'`
```
**Suggested solution:**
Add a `--no-scripts` flag to hide the description from the console.
```json
"scripts": {
    "start": "nps --no-scripts"
}
```
**Expected output:**
```shell
nps is executing `build`
nps is executing `compile`
```
(Ref: https://github.com/kentcdodds/nps/issues/119#issuecomment-306957608)

**Comment by kentcdodds** [comment]
Sounds great. In addition, I'd like this to be configurable in [options](https://github.com/kentcdodds/nps#options) (like [here](https://github.com/kentcdodds/nps/blob/master/package-scripts.js#L56-L58)) :+1:

**Comment by kentcdodds** [comment]
With `yargs`, the option will be called `scripts`, will default to `true` and be a `boolean` type. This will allow you to use `--no-scripts` to turn it off.

**Comment by erikfox** [comment]
@kentcdodds Is this ripe for pickup? Mind assigning to me?

**Comment by kentcdodds** [comment]
Thanks @erikfox! You're welcome to work on this one. I can't assign it to anyone who doesn't have commit access, but feel free to [makeapullrequest.com](http://makeapullrequest.com) for it 😄

**Comment by erikfox** [comment]
@kentcdodds PR #150 is up and needs feedback!
