### ISSUE TITLE
Fix early error

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/nps#145]
We used to have [a nice error message](https://github.com/kentcdodds/nps/blob/76bee57638e0a6158e98bdc3f2bb6c057094f6b7/src/index.js#L46-L56) when you entered a script name that didn't exist. We seem to have broken that and now we see:

```
~/Developer/glamorous (pr/with-theme)
🐿  $ nps blah
TypeError: Cannot read property 'scriptName' of undefined
    at runPackageScript (/Users/kdodds/Developer/glamorous/node_modules/nps/dist/index.js:95:35)
    at /Users/kdodds/Developer/glamorous/node_modules/nps/dist/index.js:77:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

This seems to be coming from [this](https://github.com/kentcdodds/nps/blob/76bee57638e0a6158e98bdc3f2bb6c057094f6b7/src/index.js#L45). We should probably just add `|| {}` to the end of that line. We should also have a unit test for this.

Should be pretty straightforward. Any takers?

**Comment by bhargav175** [comment]
I faced this issue when I was trying to commit the first time as well. I wanted to add myself as a contributor and then make my first PR, but that din't happen. So had to do it without add myself. I was debugging it, thought maybe I was doing something wrong. I will have a look at this one.

**Comment by kentcdodds** [comment]
Oh thanks! I didn't realize that `fish` doesn't support `&&`... Hmmm... Maybe that's something we can handle in the `nps-utils` [`series`](https://github.com/kentcdodds/nps-utils/blob/092202732ce02c71c4d4a04c9865b04ec02d19f3/src/index.js#L30-L41) util... 🤔

**Comment by bhargav175** [comment]
Yes! I was surprised that it doesn't. And the issue is in "will-not-implement" milestone. 😅 So perhaps we should find a way to not use "&&" and use "series" as you mentioned. Here you go. 
[Issue in fish shell](https://github.com/fish-shell/fish-shell/issues/150)

**Comment by kentcdodds** [comment]
Yeah, if there's a way for us to detect that you're using `fish` (I'll bet there's an npm package that'll tell you the current shell) then we could use that in `series` to determine whether to use `&&` or something else.
