### ISSUE TITLE
Unable to find a config file

### ISSUE THREAD

**Issue by jonataswalker** [kentcdodds/nps#149]
- `nps` version: `5.3.2`
- `node` version: `8.1.2`
- `npm` version: `5.0.3`

Scripts file (or at least the relevant bits):

```javascript
exports.scripts = {
  dev: {
    default: {
      script: concurrent.nps(
        'bundleDeps.browser.dev',
        'build.css.dev',
        'build.browser.dev',
        'build.server.dev',
        'server.dev'
      )
    }
}
```

### `package.json`
```json
{
  "scripts": {
    "start": "nps -c ./build/package-scripts.js"
  }
}
```

The command executed:

```console
npm start dev
```

The output:

```console
> nps -c ./build/package-scripts.js "dev"

nps is executing `dev`: node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold,bgGreen.bold,bgBlack.bold,bgCyan.bold" --prefix "[{name}]" --names "bundleDeps.browser.dev,build.css.dev,build.browser.dev,build.server.dev,server.dev" 'nps bundleDeps.browser.dev' 'nps build.css.dev' 'nps build.browser.dev' 'nps build.server.dev' 'nps server.dev'
[build.browser.dev] Unable to find a config file and none was specified.
```

Suggested solution:

Gotta pass the same config file to all subsequent scripts?

**Comment by jonataswalker** [comment]
ping @kentcdodds

**Comment by kentcdodds** [comment]
I'm on vacation. I'll get to it when I can. Thanks for your patience.

**Comment by RichDonnellan** [comment]
@jonataswalker Follow issue #139 and https://github.com/kentcdodds/nps-utils/issues/13. Sounds like you're facing the same troubles. Hopefully, it will be resolved in an upcoming release.

**Comment by jonataswalker** [comment]
Ah ok @RichDonnellan thank for pointing it.

**Comment by Miklet** [comment]
@jonataswalker Do you mind if I close this issue since there are two others you can track?

**Comment by kentcdodds** [comment]
Yeah, let's do that. Thanks @Miklet :+1:
