### ISSUE TITLE
NPS friendly badge?

### ISSUE THREAD

**Issue by Falieson** [kentcdodds/nps#157]
just a simple improvement request for the readme. 

Something I like a lot about commitizen is its badge to put at the top of my README.md telling all the devs on my team that its a commitizen project. Would like the same for NPS.

[![Commitizen friendly](https://img.shields.io/badge/commitizen-friendly-brightgreen.svg)](http://commitizen.github.io/cz-cli/)

**Comment by kentcdodds** [comment]
Sure, I'd be happy to support an official badge and mention it in the readme. How about:

[![nps friendly](https://img.shields.io/badge/nps-friendly-blue.svg?style=flat-square)](https://github.com/kentcdodds/nps)

```
[![nps friendly](https://img.shields.io/badge/nps-friendly-blue.svg?style=flat-square)](https://github.com/kentcdodds/nps)
```

**Comment by kentcdodds** [comment]
I'm partial to the flat badge look. If you'd like to [make a PR](http://makeapullrequest.com/) to add this to the README that'd be cool. Something like: "And look, you can add this badge to your project! :tada:"

**Comment by Falieson** [comment]
Thanks @kentcdodds , I'll do that today!
