### ISSUE TITLE
How to execute locally-defined function?

### ISSUE THREAD

**Issue by dkent600** [kentcdodds/nps#165]
Hi, this is just a question:

I want to execute a javascript function (as opposed to a script) using nps.  But I haven't been able to figure out how to do it.  I've defined the function in the package-script.js file in several ways but the best I have been able to get from nps is that "myFunction is not recognized as an internal or external command"

I imagine there must be some trick to doing this, but can't find any clues in all of the example code you provide.

Is this possible?

Thanks!

**Comment by kentcdodds** [comment]
Hi @dkent600,

So part of `nps` mission is to _not_ become another `gulp` where it allows you to run arbitrary JavaScript for your scripts ([it's in the roadmap](https://github.com/kentcdodds/nps/blob/master/other/ROADMAP.md)). If you want to do that, put that javascript in another file and make your script `node ./your-script`.

Good luck!

**Comment by dkent600** [comment]
Thanks, that was the clue I needed!
