### ISSUE TITLE
Allow to configure custom prefixes for scripts

### ISSUE THREAD

**Issue by SleepWalker** [kentcdodds/nps#174]
Hello, what do you think about a feature to allow user to provide custom shortcut name for script, e.g.:

```js
// ...
  storybook: {
    script: '...',
    prefix: 'sb', // or better alias because it's actually not a prefix anymore?
  }
// ...
```

and then you can run this with `nps sb`

**Comment by kentcdodds** [comment]
Hi @SleepWalker,
Thanks for the issue, but I don't think that we'll do this. The workaround is simple enough:

```js
module.exports = {scripts: {/* your scripts */}}

module.exports.scripts.sb = module.exports.scripts.storybook
```

Thanks anyway!
