### ISSUE TITLE
'Quick Video Intro' is not viewable

### ISSUE THREAD

**Issue by Enteleform** [kentcdodds/nps#176]
The linked video on Egghead.io is unviewable to the general public, marked with `This Lesson is for PRO Members`. IMO this link should be replaced with something that is freely accessible, and the Egghead.io course should be moved to a `Further Learning` / `Learning Resources` / `etc.` section at the end of the page.

**Comment by kentcdodds** [comment]
I agree. I believe it started as free and was changed. Let's move it below. Would you like to [make a pull request](http://makeapullrequest.com) to do that?
