### ISSUE TITLE
BUG: nps init does not camelCase start:* scripts

### ISSUE THREAD

**Issue by samijaber** [kentcdodds/nps#186]
- `nps` version: latest

`package.json` file:

```javascript
{
  "scripts": {
    "start": "echo start",
    "start:stuff": "echo start:stuff",
    "start:foo-bar": "echo start:foo-bar"
  }
}
```

The command executed:

```console
nps init
```

The output:

```javascript
module.exports = {
  scripts: {
    default: {
      default: 'echo start',
      stuff: 'echo start:stuff',
      foo-bar: 'echo start:foo-bar'
    }
  }
};
```

Problem description:
`foo-bar` should be `fooBar`, which means the `package-scripts.js` file generated by `nps init` is broken/invalid JS.

Suggested solution:
Raised a PR at https://github.com/kentcdodds/nps/pull/185

**Comment by kentcdodds** [comment]
Thanks!
