### ISSUE TITLE
spawn-command-with-kill, ps-tree and event-stream is not safe 

### ISSUE THREAD

**Issue by dervism** [kentcdodds/nps#190]
See:
indexzero/ps-tree#33
dominictarr/event-stream#116

When I run npm audit in my repo I get this message:
Malicious Package : nps > spawn-command-with-kill > ps-tree > event-stream > flatmap-stream

**Comment by dervism** [comment]
I have opened a pull request: https://github.com/kentcdodds/spawn-command-with-kill/pull/2 in spawn-command-with-kill.

**Comment by Germanaz0** [comment]
Can someone merge the PR ? pleaseeeee

**Comment by kentcdodds** [comment]
Merged... Wasn't flatmap-stream removed? The current version range for ps-tree should pick up the latest.... I don't see why this is necessary at all...

**Comment by kentcdodds** [comment]
But why? The version range that's already been published should include the fixed version. There is no longer a threat.

**Comment by dervism** [comment]
@kentcdodds You're right, it's not a treat now, but having the updated version of ps-tree is positive anyways. BTW: You may wanna add the range hat back on the version. I did not add it.
