### ISSUE TITLE
Wrong script getting called

### ISSUE THREAD

**Issue by pvinis** [kentcdodds/nps#191]
- `nps` version: 5.9.3
- `node` version: 10.13.0
- `npm` version: 6.4.1

Scripts file (or at least the relevant bits):

```javascript
module.exports = {
    scripts: {
        iosX: 'echo this is iosX',
        ios: 'echo this is ios',
    },
}
```

The command executed:

```console
nps ios
```

The output:

```console
nps is executing `iosX` : echo this is iosX
this is iosX
```

Problem description:
As you can see, when I run `nps ios`, even though there is a script with name exactly `ios`, nps is not calling the correct one.

Repro repo: https://github.com/pvinis/nps-bug
Screenshot:
![screenshot 2018-12-03 at 16 13 48](https://user-images.githubusercontent.com/100233/49382629-2dd45a00-f717-11e8-821d-df01e7bb11f8.png)

Suggested solution:
No idea, but for sure the `ios` script should be the one getting called.
I have the suspicion that the "smart" calling, like `nps i` "guesses" what to run, it messing up?

**Comment by kentcdodds** [comment]
Thanks! This is definitely a bug. Could you dive into this a bit and [make a PR](http://makeapullrequest.com) to fix it? Thanks!

**Comment by pvinis** [comment]
I have no idea how nps works and I don't have time to get into it. I just wanted to find a better way to manage the scripts.

**Comment by pvinis** [comment]
wat? did you make nps years ago and stopped using it?

**Comment by kentcdodds** [comment]
Yup

**Comment by kentcdodds** [comment]
I haven't used it in ~1.5 years.

**Comment by kentcdodds** [comment]
It's still definitely useful and there are plenty of people using it and loving it. But I've opted for solving my script explosion issues by making [toolkits](https://blog.kentcdodds.com/automation-without-config-412ab5e47229)

**Comment by schottilol** [comment]
Hey, this might be a little over the top for a first time contributor, but could I make a pull request for this issue? I've already got a fixed version on my local copy of the repository.

**Comment by kentcdodds** [comment]
Hi @schottilol,

Feel free to open a PR for it. I'll try to get it reviewed.
