### ISSUE TITLE
New Maintainer Needed

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/nps#193]
I haven't used this project in a very long time so I'm definitely not the right person to maintain it.

Would anyone else like to take it over?

**Comment by kevjin** [comment]
Hi Kent,
I would be interested in maintaining this project. I found out about this package not too long ago and it has been very useful for organizing our scripts in several of our projects, and can see myself using it long term as well. However, I don't have any contribution history with the project and would like to make some PRs first, I feel like that would only be right. Thanks!

**Comment by deissh** [comment]
I can become a maintainer since I use nps quite often in my home or work projects. I would like to develop nps in functionality almost to Gulp. At the moment, NPS lacks modularity and simplicity of writing complex scripts, for example, all sorts of pipelines

**Comment by kentcdodds** [comment]
If that's what you want, then I recommend starting a new project because that explicitly mentioned as something I DON'T want for this project. Thanks anyway!

**Comment by kentcdodds** [comment]
Nobody has really stepped up. Therefore I'm archiving this project. It still works today, it just wont receive new features/patches/etc.

Feel free to continue using it, but because I'm not using it, I don't have the bandwidth to maintain it.

Feel free to fork the project and republish under a new domain in accordance to the MIT license this project has.

**Comment by kentcdodds** [comment]
Hey folks, I'd like to introduce you to your new maintainer: @sezna :)

I'm handing him the keys of the kingdom. The repo will be completely transferred to him as well as the npm publish rights.

Hopefully this will help to fix bugs and add new features that people are looking for out of this package. Good luck friends! 👋

**Comment by sezna** [comment]
Ahoy! Thanks Kent!

**Comment by justin808** [comment]
@kentcdodds 

> I haven't used this project in a very long time so I'm definitely not the right person to maintain it.

What are you using instead?
