### ISSUE TITLE
syntax errors in package-scripts.js should not be swallowed.

### ISSUE THREAD

**Issue by jisaacks** [kentcdodds/nps#22]
- `p-s` version: 1.0.1
- `node` version: 6.2.1
- `npm` version: 3.9.3

Problem description:

If there is a syntax error in the `package-scripts.js` (in my case for example a missing comma) then it will fail to load. However your error message swallows the syntax error and just says that it cannot find the `package-scripts.js` file which was confusing for me.

Suggested solution:

Basically when [capturing the error here](https://github.com/kentcdodds/p-s/blob/adb01e92e111cf5a0d0c3ac4f42386bda04cc5bc/src/bin-utils.js#L86-L88)

Just add a check for syntax error:

``` javascript
if (e instanceof SyntaxError) {
   throw e;
}
```

I'll gladly make the change and submit a PR.

**Comment by kentcdodds** [comment]
Oh that's great! Yes, let's do that :+1: Thanks!

**Comment by kentcdodds** [comment]
I think this is a problem again...

**Comment by boneskull** [comment]
Indeed, my errors are getting eaten.

**Comment by boneskull** [comment]
I feel like the problem here is a lack of distinction between a *missing* config file, and one which is simply invalid.

**Comment by Miklet** [comment]
Already merged, closing :)
