### ISSUE TITLE
`init` should not move certain scripts

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/nps#97]
When you run `init`, currently it moves all the scripts to `package-scripts.js`. It would be great if we kept a list of scripts that shouldn't be moved (because they have semantic meaning in the `package.json` `scripts`).

For example, all [the npm lifecycle scripts](https://docs.npmjs.com/misc/scripts):

- prepublish
- publish
- postpublish
- preinstall
- install
- postinstall
- preuninstall
- uninstall
- postuninstall
- preversion
- version
- postversion
- pretest
- posttest
- prestop
- stop
- poststop
- prestart
- poststart
- prerestart
- restart
- postrestart

> We already have special handling for these scripts:
> - test
> - start

In addition, [`husky`](https://github.com/typicode/husky) is a personal favorite package of mine and  any of these scripts should be left untouched as well:

- applypatchmsg
- preapplypatch
- postapplypatch
- precommit
- preparecommitmsg
- commitmsg
- postcommit
- prerebase
- postcheckout
- postmerge
- prepush
- prereceive
- update
- postreceive
- postupdate
- pushtocheckout
- preautogc
- postrewrite

Another thought is if we see `npm run` in any of the scripts, perhaps we could change that to simply `nps` (unless the script referenced is in this list of scripts to keep around). This could be a little complicated, but I feel like it could be isolated pretty well and improve community adoption. Anyone wanna try their hand at this? Relevant code is [here](https://github.com/kentcdodds/p-s/tree/master/src/bin-utils/initialize).

**Comment by kwelch** [comment]
This is a dup of #128 or vise-versa.

**Comment by Miklet** [comment]
Found some time to work on that issue. Thinking about the part you mentioned at the end. Beside `npm run` I guess we should also handle: `npm run-script`, `yarn start` and `yarn`. I see one problem with `yarn`'s command. How to distinguish it from something like `yarn global`. On the other hand, I don't think that people put other `yarn` commands in `package.json` than `yarn start|yarn` 😄

**Comment by kentcdodds** [comment]
Let's just start out by supporting `npm run` :smile:

Thanks!

**Comment by Miklet** [comment]
#154 closing :)
